baseURL = "http://example.org/"
languageCode = "en-us"
title = "Polish City club"
themesDir = "themes"
theme = "gohugo-theme-ananke"

[params]
    featured_image = "/images/gohugo-default-sample-hero-image.jpg"