baseURL = "https://pawelsawicz.github.io/pcc-website/"
languageCode = "en-us"
title = "Polish City club"
themesDir = "themes"
theme = "gohugo-theme-ananke"
publishDir = "docs"
pcc_logo = "/images/pcc_circle.png"

[params]
    facebook = "https://www.facebook.com/PolishCityClub/"
    twitter = "https://twitter.com/PolishCityClub"
    linkedin = "https://www.linkedin.com/company/polish-city-club"
    featured_image = "/images/bg-1.jpeg"