baseURL = "https://pawelsawicz.github.io/pcc-website/"
languageCode = "en-us"
title = "Polish City club"
themesDir = "themes"
theme = "gohugo-theme-ananke"
publishDir = "docs"

[params]
    facebook = "https://www.facebook.com/PolishCityClub/"
    twitter = "https://twitter.com/PolishCityClub"
    linkedin = "http://www.linkedin.com/groups/Polish-City-Club-1393417/about"
    featured_image = "/images/bg-1.jpeg"